# Author: ItzRustam (Rustam Singh Bhadouriya)
# Project: NULL Multi-Agent Ecosystem | Licensed under the MIT License

"""Parsers for each Agent with safe parser option"""
"""
File Contains
* Pydantic Classes
* SafeParser Class
* Langchain pydantic parser

"""

from pydantic import BaseModel, Field, ValidationError
from langchain_core.output_parsers import PydanticOutputParser
import json
from typing import List, Dict, Any
from rich import print as rprint

class NullOutput(BaseModel):
    status: str = Field(..., description="workflow status (e.g., 'Error', 'Success')")
    response: str = Field(..., description="Detailed explanation of work and your response for user query")

# tool_used removed due to small model.
class CodOutput(BaseModel):
    status: str = Field(..., description="Execution status (e.g., 'Success', 'Failed')")
    task: str = Field(..., description="The specific given task")
    summary: str = Field(..., description="Summary of file contents read or files written")

class TechnoOutput(BaseModel):
    status: str = Field(..., description="API request status (e.g, 'Success', 'Failed')")
    task: str = Field(..., description="The API task assigned")
    summary: str = Field(..., description="Summary of the API interaction")
    api_result: Dict[str, Any] = Field(default_factory=dict, description="Raw API response data")

# Removed tool_used to stabilize the system
class AlexOutput(BaseModel):
    status: str = Field(..., description="Research status (e.g, 'Success', 'Failed')")
    content: str = Field(..., description="Synthesized research findings")
    task: str = Field(..., description="The research task assigned")

class CoreXOutput(BaseModel):
    status: str = Field(..., description="Code generation status (e.g, 'Success', 'Failed')")
    task: str = Field(..., description="The coding task assigned")
    summary: str = Field(..., description="Summary of the implementation")
    code: str = Field(..., description="Executable code generated")

def clear_text(response : str):
    """Function for clearing Text for Json Wrapper for SafeParser"""
    cleaned_text = response.replace("```json", "").replace("```", "").strip()
    return cleaned_text


class SafeParser:
    """SafeParser
    Parse Agent's Output when parser.invoke() didn't works

    Safe Parsers
    ------------
    * NULL
    * Cod
    * Alex
    * Techno
    * CoreX

    parameter
    ---------
    response: str, content generated by model
    
    NOTE: Only useful when agent has generated final response or Just when Parser Failed to parse.
    """
    @staticmethod
    # Use When Model didn't returned correct template. Only useful with result.content
    def parse_null(response : str):
        cleared_response = clear_text(response=response)
        try:
            return NullOutput.model_validate_json(cleared_response)
        except (ValidationError, json.JSONDecodeError):
            rprint("[red]LOG: Null Parser Fallback applying")

            return NullOutput(status="Idle", response=cleared_response.strip())

    @staticmethod
    def parse_cod(response : str):
        cleared_response = clear_text(response=response)
        try:
            return CodOutput.model_validate_json(cleared_response)
        
        except (ValidationError, json.JSONDecodeError):
            rprint("[red]LOG: Cod Parser Fallback applying")
            # returning by applying schema
            return CodOutput(status="Idle", response=cleared_response.strip(), task="Nothing")

    @staticmethod
    def parse_alex(response : str):
        cleared_response = clear_text(response=response)
        try:
            return AlexOutput.model_validate_json(cleared_response)
        
        except (ValidationError, json.JSONDecodeError):
            rprint("[red]LOG: Alex Parser Fallback applying")
            # returning by applying schema
            return AlexOutput(status="Idle", content=cleared_response.strip(), task="Nothing")

    @staticmethod
    def parse_techno(response : str):
        cleared_response = clear_text(response=response)
        try:
            return TechnoOutput.model_validate_json(cleared_response)
        
        except (ValidationError, json.JSONDecodeError):
            rprint("[red]LOG: Techno Parser Fallback applying")
            # returning by applying schema
            return TechnoOutput(status="Idle", summary=cleared_response.strip(), task="Nothing", api_result={"content" : "Nothing"})

    @staticmethod
    def parse_corex(response : str):
        cleared_response = clear_text(response=response)
        try:
            return CoreXOutput.model_validate_json(cleared_response)
        
        except (ValidationError, json.JSONDecodeError):
            rprint("[red]LOG: CoreX Parser Fallback applying")
            # returning by applying schema
            return CoreXOutput(status="Idle", summary=cleared_response.strip(), task="Nothing", code=" ")


# Declaring Parsers with langchain
null_parser = PydanticOutputParser(pydantic_object=NullOutput)
cod_parser = PydanticOutputParser(pydantic_object=CodOutput)
alex_parser = PydanticOutputParser(pydantic_object=AlexOutput)
techno_parser = PydanticOutputParser(pydantic_object=TechnoOutput)
corex_parser = PydanticOutputParser(pydantic_object=CoreXOutput)
